"""phase3.1 agent_actions

Revision ID: 2ba2dc778e26
Revises: 76c3bd1f529f
Create Date: 2026-07-21 16:32:42.358264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba2dc778e26'
down_revision: Union[str, Sequence[str], None] = '76c3bd1f529f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('intent_execution_id', sa.BigInteger(), nullable=True),
    sa.Column('action_log_id', sa.BigInteger(), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('execution_mode', sa.String(length=16), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('request_digest', sa.String(length=64), nullable=True),
    sa.Column('pre_state_json', sa.JSON(), nullable=True),
    sa.Column('predicted_impact_json', sa.JSON(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('provider_response_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_agent_actions_idempotency')
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_action_log_id'), ['action_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_app_id'), ['app_id'], unique=False)
        batch_op.create_index('ix_agent_actions_app_state', ['app_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_intent_execution_id'), ['intent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_step_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_state'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_intent_execution_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_entity_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_created_at'))
        batch_op.drop_index('ix_agent_actions_app_state')
        batch_op.drop_index(batch_op.f('ix_agent_actions_app_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_action_log_id'))

    op.drop_table('agent_actions')
    # ### end Alembic commands ###
