"""phase3.2 approval expiry + snapshot

Revision ID: 49d2e70677ed
Revises: 2ba2dc778e26
Create Date: 2026-07-21 17:07:19.437068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d2e70677ed'
down_revision: Union[str, Sequence[str], None] = '2ba2dc778e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_column('snapshot_json')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
