"""phase4_2 add agent_impact_jobs

Revision ID: 6aff1c23d194
Revises: eaa540e8896a
Create Date: 2026-07-22 05:53:28.339332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aff1c23d194'
down_revision: Union[str, Sequence[str], None] = 'eaa540e8896a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_impact_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('window', sa.String(length=8), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('envelope_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', 'kind', 'window', name='uq_impact_job_action_kind_window')
    )
    with op.batch_alter_table('agent_impact_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_impact_jobs_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_impact_jobs_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_impact_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_impact_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_impact_jobs_due', ['status', 'scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_impact_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_impact_jobs_due')
        batch_op.drop_index(batch_op.f('ix_agent_impact_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_impact_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_agent_impact_jobs_app_id'))
        batch_op.drop_index(batch_op.f('ix_agent_impact_jobs_action_id'))

    op.drop_table('agent_impact_jobs')
    # ### end Alembic commands ###
