"""baseline

Revision ID: 76c3bd1f529f
Revises: 
Create Date: 2026-07-21 11:01:01.655557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c3bd1f529f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_autonomy_alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_autonomy_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_autonomy_alerts_app_id'), ['app_id'], unique=False)

    op.create_table('agent_autonomy_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('n_anomalies', sa.Integer(), nullable=True),
    sa.Column('n_alerts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_autonomy_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_autonomy_scans_app_id'), ['app_id'], unique=False)

    op.create_table('agent_episodes',
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('action_label', sa.String(length=128), nullable=True),
    sa.Column('intent_class', sa.String(length=64), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('pre_state_json', sa.JSON(), nullable=True),
    sa.Column('impact_json', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('episode_id')
    )
    with op.batch_alter_table('agent_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_episodes_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_episodes_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_episodes_timestamp'), ['timestamp'], unique=False)

    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('abort_requested', sa.Boolean(), nullable=True),
    sa.Column('pending_redirect', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_key', sa.String(length=64), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_app_key'), ['app_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_apps_id'), ['id'], unique=False)

    op.create_table('dim_fx_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dim_fx_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dim_fx_rate_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_fx_rate_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_fx_rate_quote_currency'), ['quote_currency'], unique=False)

    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('visible_roles', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menus_id'), ['id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('predicted_impact_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_session_id'), ['session_id'], unique=False)

    op.create_table('agg_ua_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('app_key', sa.String(length=64), nullable=True),
    sa.Column('bundle_name', sa.String(length=128), nullable=True),
    sa.Column('media_source', sa.String(length=64), nullable=True),
    sa.Column('source_platform', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('adset_name', sa.String(length=512), nullable=True),
    sa.Column('ad_id', sa.String(length=128), nullable=True),
    sa.Column('ad_name', sa.String(length=512), nullable=True),
    sa.Column('creative_id', sa.String(length=128), nullable=True),
    sa.Column('match_status', sa.String(length=16), nullable=True),
    sa.Column('signal_confidence', sa.String(length=16), nullable=True),
    sa.Column('total_shows', sa.BigInteger(), nullable=True),
    sa.Column('total_clicks', sa.BigInteger(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_registers', sa.BigInteger(), nullable=True),
    sa.Column('total_media_installs', sa.BigInteger(), nullable=True),
    sa.Column('total_mmp_installs', sa.BigInteger(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_revenue_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('af_cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('af_cvr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('af_arpu', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ipm', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_0', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_3', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_7', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_14', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_30', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_60', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_3', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_7', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_14', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_30', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=True),
    sa.Column('forecast_version', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agg_ua_daily', schema=None) as batch_op:
        batch_op.create_index('idx_ua_agg', ['app_id', 'active_date', 'campaign_id', 'source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_active_date'), ['active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_app_key'), ['app_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_media_source'), ['media_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_agg_ua_daily_source_platform'), ['source_platform'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('media', sa.String(length=64), nullable=True),
    sa.Column('dsp', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_type', sa.String(length=64), nullable=True),
    sa.Column('objective', sa.String(length=64), nullable=True),
    sa.Column('bid_strategy', sa.String(length=64), nullable=True),
    sa.Column('optimization_goal', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_budget', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('health', sa.String(length=16), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('installs', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_media', ['app_id', 'media'], unique=False)
        batch_op.create_index('idx_campaign_status', ['app_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_media'), ['media'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('connector_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.Column('credentials_json', sa.JSON(), nullable=False),
    sa.Column('sync_frequency', sa.String(length=32), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector_credentials', schema=None) as batch_op:
        batch_op.create_index('idx_credential_platform', ['app_id', 'platform', 'account_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_connector_credentials_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_credentials_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_credentials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_credentials_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_credentials_status'), ['status'], unique=False)

    op.create_table('connector_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('app_key', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('raw_row_count', sa.Integer(), nullable=True),
    sa.Column('normalized_row_count', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('adapter_response_json', sa.JSON(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_runs_id'), ['id'], unique=False)

    op.create_table('creatives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('designer', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('installs', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creatives', schema=None) as batch_op:
        batch_op.create_index('idx_creative_status', ['app_id', 'status'], unique=False)
        batch_op.create_index('idx_creative_type', ['app_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatives_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatives_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatives_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatives_type'), ['type'], unique=False)

    op.create_table('dashboard_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    with op.batch_alter_table('dashboard_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_cache_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_cache_id'), ['id'], unique=False)

    op.create_table('dim_campaign_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_platform', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('entity_level', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('adset_name', sa.String(length=512), nullable=True),
    sa.Column('ad_id', sa.String(length=128), nullable=True),
    sa.Column('ad_name', sa.String(length=512), nullable=True),
    sa.Column('creative_id', sa.String(length=128), nullable=True),
    sa.Column('creative_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('targeting_json', sa.JSON(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('first_seen_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dim_campaign_structure', schema=None) as batch_op:
        batch_op.create_index('idx_struct_upsert', ['app_id', 'source_platform', 'entity_level', 'entity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_ad_id'), ['ad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_adset_id'), ['adset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_creative_id'), ['creative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_entity_level'), ['entity_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_campaign_structure_source_platform'), ['source_platform'], unique=False)

    op.create_table('intent_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('intent_text', sa.Text(), nullable=False),
    sa.Column('intent_class', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('affected_count', sa.Integer(), nullable=True),
    sa.Column('affected_campaigns_json', sa.JSON(), nullable=True),
    sa.Column('estimated_impact_json', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.String(length=16), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approval_deadline', sa.DateTime(), nullable=True),
    sa.Column('auto_execute_on_timeout', sa.Boolean(), nullable=True),
    sa.Column('execution_status', sa.String(length=16), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('impact_2h_json', sa.JSON(), nullable=True),
    sa.Column('impact_24h_json', sa.JSON(), nullable=True),
    sa.Column('impact_7d_json', sa.JSON(), nullable=True),
    sa.Column('model_feedback', sa.String(length=16), nullable=True),
    sa.Column('human_feedback', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actions_log_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intent_executions_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_executions_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_executions_execution_status'), ['execution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_executions_intent_class'), ['intent_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_executions_risk_level'), ['risk_level'], unique=False)

    op.create_table('report_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('creative_id', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('media_source', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('previous_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_campaigns', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('notified_channels', sa.JSON(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_alerts_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_alerts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_alerts_status'), ['status'], unique=False)

    op.create_table('report_campaign_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.String(length=128), nullable=False),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('media_source', sa.String(length=64), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_level', sa.String(length=16), nullable=True),
    sa.Column('lifecycle_phase', sa.String(length=16), nullable=True),
    sa.Column('roi_score', sa.Integer(), nullable=True),
    sa.Column('retention_score', sa.Integer(), nullable=True),
    sa.Column('spend_stability_score', sa.Integer(), nullable=True),
    sa.Column('scale_potential_score', sa.Integer(), nullable=True),
    sa.Column('roi_d7', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_d7', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('spend_trend', sa.String(length=16), nullable=True),
    sa.Column('daily_spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpi_d7', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('alert_level', sa.String(length=16), nullable=True),
    sa.Column('suggested_action', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_campaign_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_campaign_health_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_campaign_health_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_campaign_health_health_level'), ['health_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_campaign_health_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_campaign_health_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('strategy_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('total_applications', sa.Integer(), nullable=True),
    sa.Column('avg_impact_roi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_templates_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_templates_id'), ['id'], unique=False)

    op.create_table('user_app_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_app_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_app_bindings_id'), ['id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('intent_execution_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('ad_id', sa.String(length=128), nullable=True),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('impact_24h_json', sa.JSON(), nullable=True),
    sa.Column('impact_7d_json', sa.JSON(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('platform_response_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['intent_execution_id'], ['intent_executions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_logs_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_id'), ['id'], unique=False)

    op.create_table('ad_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('audience_json', sa.JSON(), nullable=True),
    sa.Column('geo_targets', sa.JSON(), nullable=True),
    sa.Column('device_types', sa.JSON(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('installs', sa.Integer(), nullable=True),
    sa.Column('cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_groups_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_groups_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_groups_status'), ['status'], unique=False)

    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('app_key', sa.String(length=64), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['connector_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payloads_id'), ['id'], unique=False)

    op.create_table('ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('creative_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('ad_type', sa.String(length=32), nullable=True),
    sa.Column('placement', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.String(length=2048), nullable=True),
    sa.Column('cta_text', sa.String(length=64), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('installs', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_ad_group_id'), ['ad_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_creative_id'), ['creative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_status'), ['status'], unique=False)

    op.create_table('fact_media_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_platform', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('app_key', sa.String(length=64), nullable=True),
    sa.Column('media_source', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('adset_name', sa.String(length=512), nullable=True),
    sa.Column('ad_id', sa.String(length=128), nullable=True),
    sa.Column('ad_name', sa.String(length=512), nullable=True),
    sa.Column('creative_id', sa.String(length=128), nullable=True),
    sa.Column('creative_name', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('spend_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('media_installs', sa.BigInteger(), nullable=True),
    sa.Column('media_conversions', sa.BigInteger(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_row_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['connector_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_row_hash')
    )
    with op.batch_alter_table('fact_media_daily', schema=None) as batch_op:
        batch_op.create_index('idx_media_agg', ['app_id', 'app_key', 'date', 'campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_ad_id'), ['ad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_adset_id'), ['adset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_app_key'), ['app_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_creative_id'), ['creative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_media_source'), ['media_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_media_daily_source_platform'), ['source_platform'], unique=False)

    op.create_table('fact_mmp_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mmp', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('app_key', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('media_source', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('adset_name', sa.String(length=512), nullable=True),
    sa.Column('ad_id', sa.String(length=128), nullable=True),
    sa.Column('ad_name', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('attribution_model', sa.String(length=32), nullable=True),
    sa.Column('signal_confidence', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('attributed_installs', sa.BigInteger(), nullable=True),
    sa.Column('registrations', sa.BigInteger(), nullable=True),
    sa.Column('payers', sa.BigInteger(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('revenue_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('roi_d0', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d3', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d7', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d14', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d30', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d60', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi_d90', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_d1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_d3', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_d7', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_d14', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retention_d30', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_row_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['connector_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_row_hash')
    )
    with op.batch_alter_table('fact_mmp_daily', schema=None) as batch_op:
        batch_op.create_index('idx_mmp_agg', ['app_id', 'app_key', 'date', 'campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_app_key'), ['app_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_mmp_daily_media_source'), ['media_source'], unique=False)

    op.create_table('ad_creative_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('creative_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_creative_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_creative_links_ad_id'), ['ad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_creative_links_creative_id'), ['creative_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_creative_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_creative_links_creative_id'))
        batch_op.drop_index(batch_op.f('ix_ad_creative_links_ad_id'))

    op.drop_table('ad_creative_links')
    with op.batch_alter_table('fact_mmp_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_media_source'))
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_id'))
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_date'))
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_country'))
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_app_key'))
        batch_op.drop_index(batch_op.f('ix_fact_mmp_daily_app_id'))
        batch_op.drop_index('idx_mmp_agg')

    op.drop_table('fact_mmp_daily')
    with op.batch_alter_table('fact_media_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_source_platform'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_media_source'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_id'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_date'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_creative_id'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_country'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_app_key'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_app_id'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_adset_id'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_ad_id'))
        batch_op.drop_index(batch_op.f('ix_fact_media_daily_account_id'))
        batch_op.drop_index('idx_media_agg')

    op.drop_table('fact_media_daily')
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_status'))
        batch_op.drop_index(batch_op.f('ix_ads_id'))
        batch_op.drop_index(batch_op.f('ix_ads_external_id'))
        batch_op.drop_index(batch_op.f('ix_ads_creative_id'))
        batch_op.drop_index(batch_op.f('ix_ads_ad_group_id'))

    op.drop_table('ads')
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_payloads_id'))

    op.drop_table('raw_payloads')
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_groups_status'))
        batch_op.drop_index(batch_op.f('ix_ad_groups_id'))
        batch_op.drop_index(batch_op.f('ix_ad_groups_external_id'))
        batch_op.drop_index(batch_op.f('ix_ad_groups_campaign_id'))

    op.drop_table('ad_groups')
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_logs_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_app_id'))

    op.drop_table('action_logs')
    op.drop_table('user_roles')
    with op.batch_alter_table('user_app_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_app_bindings_id'))

    op.drop_table('user_app_bindings')
    with op.batch_alter_table('strategy_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_templates_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_templates_category'))
        batch_op.drop_index(batch_op.f('ix_strategy_templates_app_id'))

    op.drop_table('strategy_templates')
    op.drop_table('role_permissions')
    with op.batch_alter_table('report_campaign_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_campaign_health_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_report_campaign_health_id'))
        batch_op.drop_index(batch_op.f('ix_report_campaign_health_health_level'))
        batch_op.drop_index(batch_op.f('ix_report_campaign_health_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_report_campaign_health_app_id'))

    op.drop_table('report_campaign_health')
    with op.batch_alter_table('report_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_report_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_report_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_report_alerts_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_report_alerts_app_id'))
        batch_op.drop_index(batch_op.f('ix_report_alerts_alert_type'))

    op.drop_table('report_alerts')
    with op.batch_alter_table('intent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intent_executions_risk_level'))
        batch_op.drop_index(batch_op.f('ix_intent_executions_intent_class'))
        batch_op.drop_index(batch_op.f('ix_intent_executions_id'))
        batch_op.drop_index(batch_op.f('ix_intent_executions_execution_status'))
        batch_op.drop_index(batch_op.f('ix_intent_executions_created_at'))
        batch_op.drop_index(batch_op.f('ix_intent_executions_approval_status'))
        batch_op.drop_index(batch_op.f('ix_intent_executions_app_id'))

    op.drop_table('intent_executions')
    with op.batch_alter_table('dim_campaign_structure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_source_platform'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_parent_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_entity_level'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_entity_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_creative_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_as_of_date'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_app_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_adset_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_ad_id'))
        batch_op.drop_index(batch_op.f('ix_dim_campaign_structure_account_id'))
        batch_op.drop_index('idx_struct_upsert')

    op.drop_table('dim_campaign_structure')
    with op.batch_alter_table('dashboard_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_cache_id'))
        batch_op.drop_index(batch_op.f('ix_dashboard_cache_app_id'))

    op.drop_table('dashboard_cache')
    with op.batch_alter_table('creatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creatives_type'))
        batch_op.drop_index(batch_op.f('ix_creatives_status'))
        batch_op.drop_index(batch_op.f('ix_creatives_id'))
        batch_op.drop_index(batch_op.f('ix_creatives_app_id'))
        batch_op.drop_index('idx_creative_type')
        batch_op.drop_index('idx_creative_status')

    op.drop_table('creatives')
    with op.batch_alter_table('connector_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_runs_id'))

    op.drop_table('connector_runs')
    with op.batch_alter_table('connector_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_credentials_status'))
        batch_op.drop_index(batch_op.f('ix_connector_credentials_platform'))
        batch_op.drop_index(batch_op.f('ix_connector_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_connector_credentials_app_id'))
        batch_op.drop_index(batch_op.f('ix_connector_credentials_account_id'))
        batch_op.drop_index('idx_credential_platform')

    op.drop_table('connector_credentials')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_media'))
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_external_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_country'))
        batch_op.drop_index(batch_op.f('ix_campaigns_app_id'))
        batch_op.drop_index('idx_campaign_status')
        batch_op.drop_index('idx_campaign_media')

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agg_ua_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_source_platform'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_media_source'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_id'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_country'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_app_key'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_app_id'))
        batch_op.drop_index(batch_op.f('ix_agg_ua_daily_active_date'))
        batch_op.drop_index('idx_ua_agg')

    op.drop_table('agg_ua_daily')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_session_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menus_id'))

    op.drop_table('menus')
    with op.batch_alter_table('dim_fx_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_fx_rate_quote_currency'))
        batch_op.drop_index(batch_op.f('ix_dim_fx_rate_id'))
        batch_op.drop_index(batch_op.f('ix_dim_fx_rate_as_of_date'))

    op.drop_table('dim_fx_rate')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_id'))
        batch_op.drop_index(batch_op.f('ix_apps_app_key'))

    op.drop_table('apps')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_sessions_app_id'))

    op.drop_table('agent_sessions')
    with op.batch_alter_table('agent_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_episodes_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_episodes_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_episodes_action'))

    op.drop_table('agent_episodes')
    with op.batch_alter_table('agent_autonomy_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_autonomy_scans_app_id'))

    op.drop_table('agent_autonomy_scans')
    with op.batch_alter_table('agent_autonomy_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_autonomy_alerts_app_id'))

    op.drop_table('agent_autonomy_alerts')
    # ### end Alembic commands ###
