"""phase4.1 split impact into observed and attributed

Revision ID: eaa540e8896a
Revises: 49d2e70677ed
Create Date: 2026-07-21 22:09:46.031108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa540e8896a'
down_revision: Union[str, Sequence[str], None] = '49d2e70677ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observed_impact_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attributed_impact_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('intent_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observed_impact_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attributed_impact_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_executions', schema=None) as batch_op:
        batch_op.drop_column('attributed_impact_json')
        batch_op.drop_column('observed_impact_json')

    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_column('attributed_impact_json')
        batch_op.drop_column('observed_impact_json')

    # ### end Alembic commands ###
